### ISSUE TITLE
How do I update all cache keys with current_price_list

### ISSUE THREAD

**Issue by ThomasBush** [freego/spree_price_lists#3]
Usage step 2 indicates I need to "update all cache keys with current_price_list instead of current_currency"  

How do I go about doing this?  Is this something I would have to use deface for?  I am having  difficulty figuring this out.  

I have not yet completed this step, but price show up correctly on the product#index, and incorrectly in main nav and cart view after adding -- is this a related issue or something entirely different?

**Comment by alepore** [comment]
You just have to replace all the `<% cache ...` blocks on the templates.
I'd personally copy and modify all the templates rather than use deface...

Not sure about main nav and cart view, need to check
